title: Derrik Creates
description: Livestreams about video games and programming
show_downloads: true
google_analytics: UA-155995296-1
theme: jekyll-theme-cayman
youtube: https://www.youtube.com/channel/UCsV82279p3A8jlI-LL5n2fQ?view_as=subscriber
twitch: https://www.twitch.tv/derrikcreates
discord: https://discord.gg/a2nqyqceGW
about: /about